# Generated by Django 3.2.3 on 2021-05-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('isbn13', models.CharField(max_length=13)),
                ('avg_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('publisher', models.CharField(max_length=50)),
                ('pages', models.IntegerField()),
                ('year_published', models.IntegerField()),
            ],
        ),
    ]
